site_name: Mes mémos

theme: readthedocs

nav:
    - 'Home': index.md
    - 'Linux':
        - 'Tmux': memo-tmux.md
        - 'OpenSSL': memo-openssl.md
    - 'Virtualisation':
        - 'Docker': memo-docker.md
        - 'Kvm': memo-kvm.md
